app:
  name: @project.artifactId@
  version: @project.version@
  description: @project.description@
spring:
  application:
    name: @project.name@
  cloud:
    config:
      name: @project.name@
      profile: ${PROFILE:dev}
  config:
    import: optional:configserver:${CONFIG_SERVER_URI:http://localhost:8888}
